Add files via upload

diff --git a/rtd b/rtd
--- a/rtd
+++ b/rtd
@@ -3,7 +3,7 @@
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #:: Author(s):   	SLS, KLS, NB.  Buffalo Center, IA & Avarua, Cook Islands
-    RTD_Version=1.06
+    RTD_Version=1.07
 #::
 #::
 #::	Purpose: To simplify support tasks 
@@ -109,7 +109,9 @@ LIST_HEIGHT=12
 
 # Set location to backup virtual machines to. This location must have addequate space
 # to store several copies of the virtual machine disks. This may be a network share or
-# an external storage or san mount point. 
+# an external storage or san mount point. If you do non need to backup VMs you can set 
+# this to blank or ignore it. If you do not have QEMU/KVM installed selecting this 
+# option to back up Virtual Machines in the menu will do nothing.
 VM_BACKUP_TARGET="/mnt/vmdsk/VM_BACKUP"
 
 # Terminal Color Setup definitions. These settings allow the simlified use of
@@ -131,12 +133,12 @@ export NEWT_COLORS='root=,blue '
 # Finally, should you desire using your own preseed template (answers to the install questions)
 # you should change the "PRESEED_TEMPLATE" option to point to the location of you own template. 
 RELEASE=disco
-TARGET_ISO_FILE_NAME="$RELEASE-netinstall-auto.iso"
-SOURCE_ISO_URL="http://archive.ubuntu.com/ubuntu/dists/$RELEASE/main/installer-amd64/current/images/netboot/mini.iso"
-SSH_PUBLIC_KEY_FILE="$HOME/.ssh/id_rsa.pub"
-PUT_ISO_FILE_HERE_WHEN_DONE="$HOME"
-VOLUME_TITLE="RTD Ubuntu Auto Installer"
-PRESEED_TEMPLATE="https://github.com/vonschutter/Blind_Install/raw/master/custom/preseed.template"
+TARGET_ISO_FILE_NAME=
+SOURCE_ISO_URL=
+SSH_PUBLIC_KEY_FILE=
+PUT_ISO_FILE_HERE_WHEN_DONE=
+VOLUME_TITLE=
+PRESEED_TEMPLATE=
 
 # Set location to where to log information: 
 # in the system log directory in a file named the same as this script.
@@ -155,7 +157,7 @@ LOGFILE="/var/log/${0##*/}.log"
 #::::::::::::::                                          ::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 # 
-# Below please find the executive functions of this script. These re the functions 
+# Below please find the executive functions of this script. These are the functions 
 # that actually do the work requested. 
 #
 #
@@ -185,8 +187,34 @@ check_if_password_p0wned () {
 
 
 
+convert_vdi_2_qcow2 () {
+	# Function to import a VirtualBox image to KVM. qcow is a file format for disk 
+	# image files used by QEMU, a hosted virtual machine monitor.[1] It stands for 
+	# "QEMU Copy On Write" and uses a disk storage optimization strategy that delays 
+	# allocation of storage until it is actually needed. This is the required format for 
+	# qemu/KVM virtual machines. VDI: This format is the VirtualBox-specific VirtualBox Disk Image
+	qemu-img convert -f vdi -O qcow2 $VDI $QCOW2
+}
+
+
+
+change_disk_pass () {
+	# Function to change the passphrase fo an encrypted storage device. 
+	# It will offer to change the first encrypted volume found by blockid. 
+	# It is unclear how this will work if there are multiple encrypted volumes found.
+	clear
+	echo Changing the disk encryption password for your hard drive:
+	cryptsetup luksChangeKey $(blkid | grep crypto_LUKS|  cut -d : -f 1)
+	read -p "Press  [ ENTER ] to continue:"
+
+}
+
+
 
 prepare_environment_for_iso_creation () {
+	# Function to check that all dependencies are available for manipulating the 
+	# net install ISO from Ubuntu. Subsequently, the temporary file locations 
+	# are setup and templates are downloaded. 
 	# Facilitate showing collorfull statements in terminal... 
 	set_colors
 	#Include the path to where the isofile will be put... 
@@ -209,12 +237,17 @@ prepare_environment_for_iso_creation () {
 	: "${ISOHDPFX_BIN:=$(locate isohdpfx.bin  | head -n 1)}"
 	: "${PRESEED_TEMPLATE:="https://github.com/vonschutter/Blind_Install/raw/master/custom/preseed.template"}"
 	: "${SSH_PUBLIC_KEY_FILE:="/home/$SUDO_USER/.ssh/id_rsa.pub"}"
-
+	: "${TARGET_ISO_FILE_NAME:="$RELEASE-netinstall-auto.iso"}"
+	: "${SOURCE_ISO_URL:="http://archive.ubuntu.com/ubuntu/dists/$RELEASE/main/installer-amd64/current/images/netboot/mini.iso"}"
+	: "${PUT_ISO_FILE_HERE_WHEN_DONE:="/home/$SUDO_USER"}"
+	: "${VOLUME_TITLE:="RTD Ubuntu Auto Installer"}"
 	# Find the location of the public key on this machine...
 	# This should be updated to create a key if not there... 
 	if [ ! -f "$SSH_PUBLIC_KEY_FILE" ];
 	then
 		echo "Error: public SSH key $SSH_PUBLIC_KEY_FILE not found!"
+		echo "You will need to setup automatic login using ssh manually each time oyu build a server with this media."
+		read -p "Press [Enter] to continue..."
 		# exit 1
 	fi
 
@@ -307,6 +340,8 @@ SSH_KEY_KEYGEN
 
 
 create_iso_image (){
+	# Function to generate the new ISO file from the extracted and 
+	# altered original ISO. 
     # Delete old iso file if there... 
     if [ -f "$TARGET_ISO" ]; then
             rm -f "$TARGET_ISO"
@@ -512,7 +547,7 @@ check_dependencies () {
 
 
 rtd_update_system () {
-        PUBLICATION="RuntimeData Update Manager for Linux"
+        PUBLICATION="$BRANDING Update Manager for Linux"
         VERSION="1.13 (built in)"
         # System update function. The purpose of this function is to update installed software from 
 	# distribution reopositories and the newer self contained universal software stores like 
@@ -550,22 +585,23 @@ rtd_update_system () {
 	# like to be nice and add value for as many as we can. Specially if it is this easy! :) 
 	if hash pkcon 2>/dev/null; then
 		# If package kit is available then prefer this
-		echo -e $YELLOW "Setting install options for Package Kit" $ENDCOLOR
+		echo -e $YELLOW "Using: Package Kit" $ENDCOLOR
+		pkcon -y refresh 2>> $LOGFILE
 		pkcon -y update 2>> $LOGFILE
 		#| whiptail --gauge "Updating native packages..." 6 50 0
 	elif hash yum 2>/dev/null; then
 		# If package kit is not available try yum (RedHat, Cent OS, Fedora)
-		echo -e $YELLOW "Setting install options for YUM" $ENDCOLOR
+		echo -e $YELLOW "Using: YUM" $ENDCOLOR
 		deb_software_task yum -y upgrade 2>> $LOGFILE
 	elif hash apt 2>/dev/null; then
 		# If package kit is not available try apt (Debian, Ubuntu, and all derivatives)
-		echo -e $YELLOW "Setting install options for DEB" $ENDCOLOR
+		echo -e $YELLOW "Using: DEB" $ENDCOLOR
 		deb_software_task apt-get update    
 		deb_software_task apt-get upgrade -y
 		deb_software_task apt-get autoremove -y
 	elif hash zypper 2>/dev/null; then
 		# If package kit is not available try zypper (Open SUSE)
-		echo -e $YELLOW "Setting install options for ZYPPER" $ENDCOLOR
+		echo -e $YELLOW "Using: ZYPPER" $ENDCOLOR
 		deb_software_task zypper up -y 2>> $LOGFILE
 	else
 		echo -e $YELLOW "This system does not seem to have a software managment system" $ENDCOLOR
@@ -811,6 +847,8 @@ The RTD tools run in a separate terminal that you can re connect to if you shoul
 
 
 cleanup_and_finish () {
+	# Function to remove all temporary file locations left over from building
+	# the new netinstall ISO. 
             # go back to initial directory
             cd "$CURRENT_DIR"
             # Cleanup folder structure...
@@ -838,7 +876,7 @@ cleanup_and_finish () {
 rtd_setup_choices_cli_workstation () {
 	# Function to display legacy installation options. This will install software that is usefull
 	# on a really old system, or a remote system only accessible via SSH. This may be a good 
-	# usecase if oyu happen to be in an opressed geographic locaiton where your only option is 
+	# usecase if you happen to be in an opressed geographic locaiton where your only option is 
 	# to ssh to a remote server and access email and web that way. Perfomance in these cases
 	# may be very poor over the internet (as for example with the great firewall of China). In
 	# Such a case it would be usefull to have the good old CLI software! :) 
@@ -993,22 +1031,22 @@ show_manage_vm_gui () {
 	selection=$(whiptail \
 	--backtitle "$BRANDING" \
 	--title "VM Managment Menu"  \
-	--menu "Please select what you would like to do below:" 0 0 4 \
+	--menu "Please select what you would like to do below:"  0 0 4 \
 	"1" "List all virtual machines on this system" \
 	"2" "Backup all running virtual machines on this server" \
 	"3" "Generate boot media for auto installing a virtual machine on this server (Ubuntu and others)" \
-	2>&1 1>&3)
+	2>&1 1>&3 )
 	exit_status=$?
 	exec 3>&-
 
 	case $exit_status in
 	$DIALOG_CANCEL)
-	echo "Returning to main menu..."
-	show_main_menu
+		echo "Returning to main menu..."
+		show_main_menu
 	;;
 	$DIALOG_ESC)
-	echo "Program aborted." >&2
-	exit 1
+		echo "Program aborted." >&2
+		exit 1
 	;;
 	esac
 
@@ -1057,7 +1095,7 @@ show_view_informaion_about_this_system () {
 		selection=$(whiptail \
 		--backtitle "$BRANDING" \
 		--title "System Information Menu" \
-		--menu "Please select what you would like to do below:" 0 0 4 \
+		--menu "" $HEIGHT $WIDTH $LIST_HEIGHT \
 		"1" "Show system summary" \
 		"2" "Show storage device space utilization" \
 		"3" "Show users HOME folder storage use" \
@@ -1137,7 +1175,7 @@ show_manage_software_gui () {
 	while true; do
 		exec 3>&1
 		selection=$(whiptail \
-		--backtitle "$BRANDING" --title "Software Managment Menu"  --menu "Please select what you would like to do below:" 0 0 4 \
+		--backtitle "$BRANDING" --title "Software Managment Menu"  --menu "" $HEIGHT $WIDTH $LIST_HEIGHT \
 		"1" "Update all software on this system" \
 		"2" "Show what Personal Package Archives (PPA's) are defined on this system" \
 		"3" "Remove all Personal Package Archives (PPA's) NOT in use on this system" \
@@ -1203,7 +1241,7 @@ show_main_menu () {
 			selection=$(whiptail \
 				--backtitle "$BRANDING" \
 				--title "RTD Tool Main Menu" \
-				--menu "Please tell me what I can do for you:" $HEIGHT $WIDTH $LIST_HEIGHT \
+				--menu "" $HEIGHT $WIDTH $LIST_HEIGHT \
 				"1" "View information about this system" \
 				"2" "Manage Software on this system" \
 				"3" "Manage KVM on this system" \
@@ -1244,7 +1282,7 @@ show_main_menu () {
 				show_manage_vm_gui
 			;;
 			4 )
-				check_if_password_p0wned
+				show_manage_crypt_sec
 			;;
 			5 )
 				display_notice
@@ -1255,6 +1293,56 @@ show_main_menu () {
 				clear
 				rtd_update_system 
 				read -p "Press [Enter] key to return to the main menu: "
+			;;
+		esac
+	done
+}
+
+
+
+show_manage_crypt_sec () {
+	while true; do
+		exec 3>&1
+		# Dialog Display Menu Items... 
+			selection=$(whiptail \
+				--backtitle "$BRANDING" \
+				--title "Manage encryption phrases and passwords" \
+				--menu "" $HEIGHT $WIDTH $LIST_HEIGHT \
+				"1" "Check if a password is stolen" \
+				"2" "Change systems disk encrytion pass phrase" \
+				"3" "Change "$SUDO_USER" password" \
+				2>&1 1>&3)
+			exit_status=$?
+			exec 3>&-
+
+		# Cases for how program exited... 
+		case $exit_status in
+			$DIALOG_CANCEL)
+				clear
+				echo "Program terminated."
+				show_main_menu
+			;;
+			$DIALOG_ESC)
+				clear
+				echo "Program aborted." >&2
+				exit 1
+			;;
+		esac
+
+		# What to do depending on selection... 
+		case $selection in
+			0 )
+				clear
+				echo "Program terminated."
+			;;
+			1 )
+				check_if_password_p0wned
+			;;
+			2 )
+				change_disk_pass
+			;;
+			3 )
+				passwd $SUDO_USER
 			;;
 		esac
 	done
@@ -1364,7 +1452,7 @@ if [[ "$TERM" == screen* ]]; then
 else 	
 	if hash byobu 2>/dev/null; then
 		byobu new-session -s "RTD Simple Server Support Tools" "$0 $@"
-		clear
+		#clear
 	else
 		check_dependencies byobu && echo -e $RED "A critical component needed for this script to work properly was attempted to be added... Attempting to run the script again!" $ENDCOLOR 
 		su -c "$0 $@" $SUDO_USER 
